version: "3.9"
services:
  tslab-extended:
    container_name: "tslab-extended"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/node/tslab-examples/notebooks
    env_file:
      - ./.env